"""The dbt project as one Airflow task per model.

The alternative is a single task running `dbt build`. That works, and it makes
a failure opaque: the task is red, and which of ten models broke is a question
answered by reading the log. With one task per model the graph in Airflow is
the graph in dbt, a failure is visible where it happened, and a fix can be
re-run from that model forward instead of from the beginning.

    make dag-run DAG=dbt_platform

---------------------------------------------------------------------------
 How this runs, and why it is not the usual arrangement
---------------------------------------------------------------------------
 Cosmos normally executes models in-process: dbt is installed in the Airflow
 image, the project is mounted, and each task calls dbt directly. That is
 simpler and faster, and it puts the SQL in a mounted directory rather than in
 a versioned image — which is the opposite of how every other job in this
 repository works.

 ExecutionMode.DOCKER keeps the arrangement intact. Each model runs as a
 container from dataplatform/dbt, with the project baked in, started and
 discarded. Airflow needs only the manifest to build the graph; it has no dbt,
 no adapter and no database driver.

 The manifest is generated by `make manifest` in 07-dbt and mounted read-only.
 It has to exist before this DAG can be parsed — a DAG that describes a
 project it cannot read is not a DAG.
"""
from __future__ import annotations

import os
from pathlib import Path

import pendulum
from cosmos import (
    DbtTaskGroup,
    ExecutionConfig,
    ExecutionMode,
    ProfileConfig,
    ProjectConfig,
    RenderConfig,
)
from cosmos import (
    DbtTaskGroup,
    ExecutionConfig,
    ExecutionMode,
    ProfileConfig,
    ProjectConfig,
    RenderConfig,
    TestBehavior,
)
from airflow import DAG

# Mounted from 07-dbt/project by the compose file in that stack. Read-only:
# Airflow reads the manifest and the profile, and writes nothing here.
DBT_PROJECT_DIR = Path(os.environ.get("DBT_PROJECT_DIR", "/opt/dbt-project"))
DBT_IMAGE = os.environ.get("DBT_IMAGE", "dataplatform/dbt:0.1.0")

# ---------------------------------------------------------------------------
#  What Cosmos reads to build the graph
# ---------------------------------------------------------------------------
#  LoadMode.DBT_MANIFEST, not DBT_LS. DBT_LS would run `dbt ls` at parse time,
#  which needs dbt installed here and a live database connection — every time
#  the DAG file is parsed, which is every thirty seconds.
#
#  Reading a manifest costs nothing and needs neither. The trade is that the
#  manifest has to be regenerated when the models change; `make manifest` in
#  07-dbt does that, and the smoke test there checks it is not stale.
# ---------------------------------------------------------------------------
project_config = ProjectConfig(
    manifest_path=DBT_PROJECT_DIR / "target" / "manifest.json",
    project_name="bigdata_platform",
)

# Cosmos requires a profile even in Docker mode, where the container has its
# own. Pointing at the mounted one keeps them the same file rather than two
# copies that drift.
profile_config = ProfileConfig(
    profile_name="bigdata_platform",
    target_name="dev",
    profiles_yml_filepath=DBT_PROJECT_DIR / "profiles.yml",
)

execution_config = ExecutionConfig(
    execution_mode=ExecutionMode.DOCKER,
    # Required in every execution mode, and it means different things in each.
    #
    # Here it is the path inside the dbt CONTAINER, not in Airflow: Cosmos
    # passes it to the container it starts, and the Dockerfile copies the
    # project to /dbt. Airflow's own copy at /opt/dbt-project is only read for
    # the manifest and the profile, which is what ProjectConfig points at.
    #
    # Leaving it out fails at parse time with
    #     ExecutionConfig.dbt_project_path is required for the execution of
    #     dbt tasks in all execution modes
    # which is accurate and says nothing about which of the two paths it wants.
    dbt_project_path="/dbt",
)

render_config = RenderConfig(
    # Every model and every test.
    #
    # test_behavior takes a TestBehavior member, not a string. A string does
    # not match any member and Cosmos renders no tests at all — silently, with
    # the graph looking complete and fifty assertions quietly absent from it.
    #
    # AFTER_EACH attaches each test to the model it covers, so a failing
    # uniqueness check is a red task next to the model that broke it. The
    # alternative, AFTER_ALL, collects them into one task at the end — which
    # is what a single `dbt build` already gives, and gives up the reason for
    # using Cosmos in the first place.
    select=[],
    test_behavior=TestBehavior.AFTER_EACH,
)

# Everything the dbt container needs. The same variables the Makefile in
# 07-dbt passes — profiles.yml and the macros read them through env_var, so
# the image carries no addresses of its own.
DBT_ENV = {
    "CLICKHOUSE_HOST": "clickhouse-01",
    "CLICKHOUSE_PORT": "9000",
    "CLICKHOUSE_USER": "default",
    "CLICKHOUSE_PASSWORD": "",
    "DBT_SCHEMA": "marts",
    "DBT_TARGET": "dev",
    "SOURCE_DATABASE": "analytics",
    "POSTGRES_HOST": "postgres",
    "POSTGRES_PORT": "5432",
    "POSTGRES_DB": "shop",
    "POSTGRES_USER": "app",
    "POSTGRES_PASSWORD": "app",
    "S3_ENDPOINT": "http://minio:9000",
    "S3_ACCESS_KEY": "minioadmin",
    "S3_SECRET_KEY": "minioadmin",
    "S3_BUCKET_STAGED": "staged",
}

with DAG(
    dag_id="dbt_platform",
    description="The dbt project, one task per model, each in its own container",
    schedule="0 3 * * *",
    start_date=pendulum.datetime(2026, 9, 1, tz="UTC"),
    catchup=False,
    max_active_runs=1,
    tags=["07-dbt", "cosmos"],
    default_args={"retries": 1, "retry_delay": pendulum.duration(minutes=2)},
) as dag:

    dbt = DbtTaskGroup(
        group_id="dbt",
        project_config=project_config,
        profile_config=profile_config,
        execution_config=execution_config,
        render_config=render_config,
        operator_args={
            "image": DBT_IMAGE,
            # Without this the container joins the default bridge, where
            # clickhouse-01 does not resolve — and the failure reads as a
            # database problem rather than a networking one.
            "network_mode": "dataplatform",
            "docker_url": "unix://var/run/docker.sock",
            "auto_remove": "success",
            # Airflow would otherwise mount a temp directory that exists
            # inside the scheduler container and not on the host running the
            # daemon.
            "mount_tmp_dir": False,
            "environment": DBT_ENV,
        },
    )
